###############################################################################
# PACKAGE: caravan_power.yaml  (LAB + PRODUCTION READY)
# Version: v1.0.0
#
# Purpose:
# - Canonical battery sensors (Voltage/Current/Power/SoC) with robust source
#   selection (SmartShunt -> BMS -> IP22 if fresh).
# - Freshness heartbeat + package health binary sensor.
# - Alerting automations for Critical + Draining Fast.
# - View-mode input_select + UI status helper.
#
# Notes (GitHub / Security):
# - This package contains NO secrets (no SSIDs, passwords, MACs, bindkeys, IPs).
# - Device-specific entity_ids (e.g., switch.plugz01) may need adaptation.
#
# Reduce DB churn:
# - TTG is trigger-based (1/min), not BLE advert rate.
# - Canonical battery sensors are trigger-based on upstream state changes.
###############################################################################

template:
  # ============================================================
  # Trigger-based: Caravan Time To Go (reduce DB churn)
  # ============================================================
  - trigger:
      - platform: time_pattern
        minutes: "/1"
      - platform: homeassistant
        event: start
    sensor:
      - name: "Caravan Time To Go"
        unique_id: caravan_time_to_go
        unit_of_measurement: "min"
        icon: mdi:timer-sand
        state: >
          {% set ttg = states('sensor.caravan_env_1_smartshunt_time_to_go') %}
          {% set v = ttg | float(none) %}
          {% if v is none %}
            unknown
          {% else %}
            {{ v | round(0) | int }}
          {% endif %}
        attributes:
          hours: >
            {% set v = this.state | float(0) %}
            {{ (v // 60) | int }}
          minutes: >
            {% set v = this.state | float(0) %}
            {{ (v % 60) | int }}

  # ============================================================
  # Caravan Power Package Heartbeat
  # - Updates every 30s
  # - Used to verify template engine + package health
  # ============================================================
  - trigger:
      - platform: time_pattern
        seconds: "/30"
      - platform: homeassistant
        event: start
    sensor:
      - name: "Caravan Power Heartbeat"
        unique_id: caravan_power_heartbeat
        icon: mdi:heart-pulse
        state: "{{ now().timestamp() | int }}"
        attributes:
          updated_at: "{{ now() }}"
          mains_present: "{{ states('binary_sensor.caravan_mains_present') }}"
          shunt_fresh: "{{ states('binary_sensor.smartshunt_data_fresh') }}"
          ip22_fresh: "{{ states('binary_sensor.victron_ip22_data_fresh') }}"

  # ============================================================
  # Trigger-based: Canonical battery sensors (reliably update)
  # ============================================================
  - trigger:
      - platform: state
        entity_id:
          - sensor.caravan_env_1_smartshunt_battery_voltage
          - sensor.caravan_env_1_humsienk_total_voltage
          - sensor.caravan_env_1_victron_battery_voltage
          - binary_sensor.victron_ip22_data_fresh
      - platform: homeassistant
        event: start
    sensor:
      - name: "Caravan Battery Voltage"
        unique_id: caravan_battery_voltage
        unit_of_measurement: "V"
        device_class: voltage
        state_class: measurement
        state: >
          {% set shunt = states('sensor.caravan_env_1_smartshunt_battery_voltage') %}
          {% set bms   = states('sensor.caravan_env_1_humsienk_total_voltage') %}
          {% set ip22  = states('sensor.caravan_env_1_victron_battery_voltage') %}
          {% set ip22_fresh = is_state('binary_sensor.victron_ip22_data_fresh','on') %}
          {% if shunt not in ['unknown','unavailable','none',''] %}
            {{ shunt | float(0) }}
          {% elif bms not in ['unknown','unavailable','none',''] %}
            {{ bms | float(0) }}
          {% elif ip22_fresh and ip22 not in ['unknown','unavailable','none',''] %}
            {{ ip22 | float(0) }}
          {% else %}
            unknown
          {% endif %}

  - trigger:
      - platform: state
        entity_id:
          - sensor.caravan_env_1_smartshunt_battery_current
          - sensor.caravan_env_1_humsienk_current
          - sensor.caravan_env_1_victron_battery_current
          - binary_sensor.victron_ip22_data_fresh
      - platform: homeassistant
        event: start
    sensor:
      - name: "Caravan Battery Current"
        unique_id: caravan_battery_current
        unit_of_measurement: "A"
        device_class: current
        state_class: measurement
        state: >
          {% set shunt = states('sensor.caravan_env_1_smartshunt_battery_current') %}
          {% set bms   = states('sensor.caravan_env_1_humsienk_current') %}
          {% set ip22  = states('sensor.caravan_env_1_victron_battery_current') %}
          {% set ip22_fresh = is_state('binary_sensor.victron_ip22_data_fresh','on') %}
          {% if shunt not in ['unknown','unavailable','none',''] %}
            {{ shunt | float(0) }}
          {% elif bms not in ['unknown','unavailable','none',''] %}
            {{ bms | float(0) }}
          {% elif ip22_fresh and ip22 not in ['unknown','unavailable','none',''] %}
            {{ ip22 | float(0) }}
          {% else %}
            unknown
          {% endif %}

  - trigger:
      - platform: state
        entity_id:
          - sensor.caravan_env_1_smartshunt_battery_power
          - sensor.caravan_env_1_humsienk_power
          - sensor.caravan_env_1_victron_battery_power
          - binary_sensor.victron_ip22_data_fresh
      - platform: homeassistant
        event: start
    sensor:
      - name: "Caravan Battery Power"
        unique_id: caravan_battery_power
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        state: >
          {% set shunt = states('sensor.caravan_env_1_smartshunt_battery_power') %}
          {% set bms   = states('sensor.caravan_env_1_humsienk_power') %}
          {% set ip22  = states('sensor.caravan_env_1_victron_battery_power') %}
          {% set ip22_fresh = is_state('binary_sensor.victron_ip22_data_fresh','on') %}
          {% if shunt not in ['unknown','unavailable','none',''] %}
            {{ shunt | float(0) }}
          {% elif bms not in ['unknown','unavailable','none',''] %}
            {{ bms | float(0) }}
          {% elif ip22_fresh and ip22 not in ['unknown','unavailable','none',''] %}
            {{ ip22 | float(0) }}
          {% else %}
            unknown
          {% endif %}

  - trigger:
      - platform: state
        entity_id:
          - sensor.caravan_env_1_smartshunt_soc
          - sensor.caravan_env_1_humsienk_soc
          - input_number.caravan_battery_soc
      - platform: homeassistant
        event: start
    sensor:
      - name: "Caravan Battery SoC"
        unique_id: caravan_battery_soc
        unit_of_measurement: "%"
        device_class: battery
        state_class: measurement
        state: >
          {% set shunt = states('sensor.caravan_env_1_smartshunt_soc') %}
          {% set bms   = states('sensor.caravan_env_1_humsienk_soc') %}
          {% set demo  = states('input_number.caravan_battery_soc') %}
          {% if shunt not in ['unknown','unavailable','none',''] %}
            {{ shunt | float(0) }}
          {% elif bms not in ['unknown','unavailable','none',''] %}
            {{ bms | float(0) }}
          {% elif demo not in ['unknown','unavailable','none',''] %}
            {{ demo | float(0) }}
          {% else %}
            unknown
          {% endif %}

  - binary_sensor:
      - name: "Caravan Power Package Healthy"
        unique_id: caravan_power_package_healthy
        device_class: problem
        state: >
          {% set age = (now().timestamp() | int) - (states('sensor.caravan_power_heartbeat') | int(0)) %}
          {{ age > 120 }}
        attributes:
          heartbeat_age_sec: >
            {{ (now().timestamp() | int) - (states('sensor.caravan_power_heartbeat') | int(0)) }}
          threshold_sec: 120

      - name: Caravan Charging Detected
        unique_id: caravan_charging_detected
        icon: mdi:battery-charging
        state: |
          {% set v = states('sensor.caravan_battery_voltage')|float(none) %}
          {% set dv = states('sensor.caravan_batt_v_15m_change')|float(none) %}
          {% set min_v = states('input_number.caravan_charge_detect_min_v')|float(13.3) %}
          {% set min_rise = states('input_number.caravan_charge_detect_min_rise_v')|float(0.15) %}
          {% if v is none or dv is none %}
            false
          {% else %}
            {{ (v >= min_v) and (dv >= min_rise) }}
          {% endif %}
        delay_on: 00:05:00
        delay_off: 00:10:00
        attributes:
          v_now: "{{ states('sensor.caravan_battery_voltage') }}"
          v_change_15m: "{{ states('sensor.caravan_batt_v_15m_change') }}"
          min_v: "{{ states('input_number.caravan_charge_detect_min_v') }}"
          min_rise_15m: "{{ states('input_number.caravan_charge_detect_min_rise_v') }}"

      - name: Caravan Battery Draining Fast
        unique_id: caravan_battery_draining_fast
        icon: mdi:trending-down
        state: |
          {% set mains = is_state('binary_sensor.caravan_mains_present','on') %}
          {% set v = states('sensor.caravan_battery_voltage')|float(none) %}
          {% set d = states('sensor.caravan_batt_v_15m_change')|float(none) %}
          {% if mains or v is none or d is none %}
            false
          {% else %}
            {{ d <= -0.20 }}
          {% endif %}
        delay_on: 00:05:00
        delay_off: 00:10:00
        attributes:
          v_now: "{{ states('sensor.caravan_battery_voltage') }}"
          v_change_15m: "{{ states('sensor.caravan_batt_v_15m_change') }}"

      - name: "Caravan Mains Present"
        unique_id: caravan_mains_present
        device_class: power
        state: >
          {% set sw = is_state('switch.plugz01', 'on') %}
          {% set w  = states('sensor.plugz01_power')|float(0) %}
          {% set a  = states('sensor.plugz01_current')|float(0) %}
          {{ sw and (w >= 2 or a >= 0.05) }}
        delay_on: "00:00:02"
        delay_off: "00:00:02"
        attributes:
          sw: "{{ states('switch.plugz01') }}"
          w: "{{ states('sensor.plugz01_power') }}"
          a: "{{ states('sensor.plugz01_current') }}"
          v: "{{ states('sensor.plugz01_voltage') }}"

      - name: "Caravan Charger Plug On"
        unique_id: caravan_charger_plug_on
        device_class: power
        state: "{{ is_state('switch.plugz01','on') }}"

      - name: "Caravan Battery Charging Now"
        unique_id: caravan_battery_charging_now
        icon: mdi:battery-charging
        state: >
          {% set shunt_ok = is_state('binary_sensor.smartshunt_data_fresh','on') %}
          {% set i = states('sensor.caravan_env_1_smartshunt_battery_current')|float(none) %}
          {{ shunt_ok and i is not none and i > 0.30 }}

      - name: "Caravan Alternator Charging"
        unique_id: caravan_alternator_charging
        icon: mdi:engine
        state: >
          {% set present = is_state('input_boolean.caravan_orion_present','on') %}
          {% if present %}
            {% set sw = is_state('input_boolean.caravan_orion_charging','on') %}
            {% set i = states('input_number.caravan_orion_output_current')|float(0) %}
            {% set p = states('input_number.caravan_orion_output_power')|float(0) %}
            {{ sw or i > 1.0 or p > 30 }}
          {% else %}
            false
          {% endif %}
        attributes:
          lab_present: "{{ is_state('input_boolean.caravan_orion_present','on') }}"
          lab_switch: "{{ is_state('input_boolean.caravan_orion_charging','on') }}"
          lab_i_a: "{{ states('input_number.caravan_orion_output_current') }}"
          lab_p_w: "{{ states('input_number.caravan_orion_output_power') }}"

  - sensor:
      - name: "Caravan Batt V 15m Change"
        unique_id: caravan_batt_v_15m_change_template
        unit_of_measurement: "V"
        state: >
          {% set candidates = [
            'sensor.caravan_batt_v_15m_change',
            'sensor.caravan_battery_voltage_15m_change',
            'sensor.caravan_battery_voltage_15m_change_2'
          ] %}
          {% for e in candidates %}
            {% if states(e) not in ['unknown','unavailable','none',''] %}
              {{ states(e) }}
              {% break %}
            {% endif %}
          {% endfor %}

      - name: "Caravan Battery Voltage Change (15m)"
        unique_id: caravan_battery_voltage_change_15m
        unit_of_measurement: "V"
        state: >
          {{ states('sensor.caravan_batt_v_15m_change') }}

      - name: "Caravan Battery Status"
        unique_id: caravan_battery_status
        state: >
          {% set soc = states('sensor.caravan_battery_soc')|float(none) %}
          {% if soc is none %}
            Unknown
          {% elif soc <= 15 %}
            Critical
          {% elif soc <= 30 %}
            Low
          {% elif soc <= 60 %}
            OK
          {% else %}
            Good
          {% endif %}

      - name: "Caravan Consumed Ah"
        unique_id: caravan_consumed_ah
        unit_of_measurement: "Ah"
        state: >
          {% set shunt = states('sensor.caravan_env_1_smartshunt_consumed_ah') %}
          {% if shunt not in ['unknown','unavailable','none',''] %}
            {{ shunt | float(0) }}
          {% else %}
            unknown
          {% endif %}

      - name: "Caravan Charging Phase"
        unique_id: caravan_charging_phase
        state: >
          {% set s = states('sensor.caravan_env_1_victron_device_state')|float(none) %}
          {% set map = {
            0:'Init', 1:'Bulk', 2:'Absorb', 3:'Float', 4:'Storage',
            5:'ForceAbs', 6:'ForceAbs', 7:'Equalize', 8:'BulkStop', 9:'Unknown'
          } %}
          {% if s is none %}
            Unknown
          {% else %}
            {{ map.get(s|int, 'Unknown') }}
          {% endif %}

      - name: "Caravan Power Source"
        unique_id: caravan_power_source
        state: >
          {% if is_state('binary_sensor.caravan_mains_present', 'on') %}
            Mains
          {% elif is_state('binary_sensor.caravan_alternator_charging', 'on') %}
            Alternator
          {% elif is_state('binary_sensor.caravan_mains_present', 'unknown')
                or is_state('binary_sensor.caravan_mains_present', 'unavailable') %}
            Unknown
          {% else %}
            Battery
          {% endif %}

      - name: "Caravan Battery UI Status"
        unique_id: caravan_battery_ui_status
        state: >-
          {% set st = states('sensor.caravan_battery_status') %}
          {% set src = states('sensor.caravan_power_source') %}
          {% set charging = is_state('binary_sensor.caravan_battery_charging_now','on') %}
          {% if st in ['Critical','Low'] %}
            ATTENTION
          {% elif charging and src in ['Mains','Alternator'] %}
            CHARGING
          {% else %}
            OK
          {% endif %}
        attributes:
          message: >-
            {% set st = states('sensor.caravan_battery_status') %}
            {% set src = states('sensor.caravan_power_source') %}
            {% set charging = is_state('binary_sensor.caravan_battery_charging_now','on') %}
            {% if st == 'Critical' %}
              Battery critical — charge now
            {% elif st == 'Low' %}
              Battery low — consider charging
            {% elif charging and src == 'Mains' %}
              Charging from mains
            {% elif charging and src == 'Alternator' %}
              Charging from alternator
            {% elif src == 'Mains' %}
              Mains present (not charging)
            {% else %}
              Battery running normally
            {% endif %}
          color: >-
            {% set s = states('sensor.caravan_battery_ui_status') %}
            {% if s == 'ATTENTION' %}orange
            {% elif s == 'CHARGING' %}blue
            {% elif s == 'OK' %}green
            {% else %}grey
            {% endif %}

sensor:
  - platform: statistics
    name: "Caravan Battery Voltage (15m Mean)"
    unique_id: caravan_batt_v_15m_mean
    entity_id: sensor.caravan_battery_voltage
    state_characteristic: mean
    max_age:
      minutes: 15

  - platform: statistics
    name: "Caravan Battery Voltage (15m Change)"
    unique_id: caravan_batt_v_15m_change
    entity_id: sensor.caravan_battery_voltage
    state_characteristic: change
    max_age:
      minutes: 15

input_boolean:
  caravan_orion_present:
    name: "Orion present (lab)"
    icon: mdi:car-battery

  caravan_orion_charging:
    name: "Alternator charging (lab)"
    icon: mdi:engine

input_number:
  caravan_battery_soc:
    name: "Caravan Battery SoC (Demo)"
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    mode: slider

  caravan_charge_detect_min_v:
    name: "Charge detect: min voltage"
    min: 12.0
    max: 14.8
    step: 0.05
    unit_of_measurement: "V"
    initial: 13.3

  caravan_charge_detect_min_rise_v:
    name: "Charge detect: 15m rise"
    min: 0.05
    max: 0.80
    step: 0.05
    unit_of_measurement: "V"
    initial: 0.15

  caravan_orion_output_current:
    name: "Orion output current (lab)"
    min: 0
    max: 50
    step: 0.1
    unit_of_measurement: "A"
    mode: slider

  caravan_orion_output_power:
    name: "Orion output power (lab)"
    min: 0
    max: 800
    step: 1
    unit_of_measurement: "W"
    mode: slider

input_select:
  caravan_power_view:
    name: Caravan Power View
    options:
      - Auto
      - 220V
      - Battery
    initial: Auto
    icon: mdi:swap-horizontal

automation:
  - id: "caravan_power_critical_alert"
    alias: "Caravan - Power: Critical alert"
    trigger:
      - platform: state
        entity_id: sensor.caravan_battery_status
        to: Critical
        for: "00:02:00"
    condition:
      - condition: state
        entity_id: binary_sensor.caravan_mains_present
        state: "off"
      - condition: state
        entity_id: binary_sensor.caravan_charging_detected
        state: "off"
    action:
      - action: script.caravan_notify
        data:
          title: Caravan Power
          message: >
            {% set v = states('sensor.caravan_battery_voltage')|float(none) %}
            Battery CRITICAL{% if v is not none and v > 0 %} ({{ '%.2f'|format(v) }} V){% endif %}.
            {% if is_state('sensor.caravan_uplink_router','Cellular') %}On LTE.{% endif %}
          severity: alarm
    mode: single

  - id: "caravan_power_draining_fast_attention"
    alias: "Caravan - Power: Draining fast (Attention)"
    trigger:
      - platform: state
        entity_id: binary_sensor.caravan_battery_draining_fast
        to: "on"
        for: "00:05:00"
    condition:
      - condition: state
        entity_id: binary_sensor.caravan_mains_present
        state: "off"
      - condition: state
        entity_id: binary_sensor.caravan_charging_detected
        state: "off"
    action:
      - action: script.caravan_notify
        data:
          title: Caravan Power
          message: >
            Battery is draining fast. 15m change: {{ states('sensor.caravan_batt_v_15m_change') }} V.
          severity: attention
    mode: single
